MeberAdd Rename & Login Api Create
f-lab-edu/Starlucks pull request #13
Opened 2023-02-06 00:28 UTC by gyhcom

2023-02-06 04:52 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/config/MemberAddRepositoryConfig.java
> +            }
inMemory까지 구현하는게 좋을 것 같습니다.

2023-02-06 05:27 UTC, JisuNa commented
1. `MainApplication`에서 충돌이 발생했는데, PR 올리시기전에 작업 브랜치에서 main rebase를 하시고 올리시면 충돌 발생을 줄일 수 있습니다.

2. 새로운 브랜치를 작업하실 때 로컬의 main 브랜치를 최신화하고 새로 브랜치를 따서 작업하셔야 최신 코드에서 작업이 시작될 수 있습니다.
다른 브랜치의 코드를 사용하시기 위해서 `feature/12` 브랜치에서 다른 feature 브랜치들을 머지하신걸로 추측되는데, 이 방식보다는 `cherry-pick`을 사용하시는게 좋다고 생각되네요. 

3. 커밋이 17개가 있는데, 커밋을 작게 나누어하는 것도 좋지만 개인적으로는 작업이 크지 않다면 적은게 좋다고 생각합니다. 
또한 협업에 관점에서 중복되는 메시지도 있고 해당 커밋에서 어떤 작업을 했는지 알기 쉽지 않은 것 같습니다. [커밋메시지 컨벤션](https://velog.io/@archivvonjang/Git-Commit-Message-Convention)을 사용하는 것을 추천드립니다.

2023-02-06 10:22 UTC, gyhcom commented
네 감사합니다! 말해주신 내용 참고하여 다음 작업때 반영하겠습니다 :)

2023-02-06 10:26 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/config/MemberAddRepositoryConfig.java
> +            }
네네 알겠습니다.

2023-02-10 12:41 UTC, gyhcom reviewed
@JisuNa inMemory 구현했습니다.

2023-02-11 04:59 UTC, JisuNa commented
실제 로그에 남기 때문에 PR의 제목을 `Add Member signUp api`로 수정해서 제목만이라도 커밋 메시지 컨벤션 맞추면 좋을 것 같아요.

Login Api도 Controller만 작성하셨는데, main으로 머지되는 것이라 개발된 코드만 PR에 올리는게 좋습니다. 
이번 PR에서는 제거 안하고 진행하시죠.

또한 Conflict이 발생했는데 해결해야 PR 머지가 가능합니다.
`Resolve conflicts` 버튼 눌러서 해결하는 것 보다 Git 메커니즘을 이해하시기 위해서 git 커맨드로 해결하시는 방법을 추천드립니다.

```
$ git fetch --all
$ git rebase upstream/main
$ git push -f
```

마지막으로 PR을 머지하실 때 `Squash and Merge`와 `Rebase and Merge` 2가지 방식으로 머지를 할 수 있는데 [merge 이해하기](https://im-developer.tistory.com/182) 참고하시면 머지하실 때 좋습니다. 특히 이번 PR에는 커밋 17개가 로그에 들어가면 보기 좋지 않을 것 같아요.

2023-02-11 07:35 UTC, JisuNa requested changes

2023-02-11 07:35 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/config/MemberAddRepositoryConfig.java
> +        };
Config에 로직이 들어가는것보다 `InMemoryMemberRepository` 작성하는건 어떨까요.

`System.out.println("");` 도 프로덕트 코드에 포함되지 않는게 좋습니다.

`MemberAdd`는 엔티티가 아닌데 저장되는 것도 조금 이상하고, return 타입이 `MemberAdd`인데 null을 리턴하는 것도 좋지 않은 것 같습니다.

`NumberBaseBall` 공유해주셨던것과 비교해서 작업 부탁드립니다.

2023-02-11 09:21 UTC, gyhcom commented
Squash and Merge 진행하도록 하겠습니다

2023-02-11 09:21 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/config/MemberAddRepositoryConfig.java
> +        };
구성에 대해 다시 고민해서 적용하겠습니다

2023-02-12 14:22 UTC, closed without merging