Feat: 회원 가입 JPA 기능 구현
f-lab-edu/Starlucks pull request #22
Opened 2023-02-21 12:26 UTC by gyhcom

Common ErrorCode, ApiResponse 추가
Jpa Api Test 완료
테이블 구조 수정 필요
flyWay 적용 예정

2023-02-27 04:12 UTC, JisuNa requested changes

2023-02-27 04:12 UTC, JisuNa commented on starlucks-main/src/main/resources/db/migration/V1.0__init_ddl.sql
> +);
컬럼명은 소문자가 좋을 것 같아요. [명명규칙](https://velog.io/@ohsol/MySQL-DB-%EB%AA%85%EB%AA%85-%EA%B7%9C%EC%B9%99-%EC%A0%95%EB%A6%AC)

2023-02-27 04:12 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/domain/entity/Member.java
>      private Long id;
`id`로 사용하면 다른 테이블이랑 혼동될 수 있을 것 같습니다. `memberId`과 같이 구분되는게 어떨까요

2023-02-27 04:12 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        String pass = command.getPassword();
pass 변수명도 조금 맞지 않아 보이고, `String pass =`로 담아서 argument로 넘기신 이유가 있을까요?

2023-02-27 04:12 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/application/command/MemberAddCommand.java
> +    public Member toEntity(String password) {
password를 parameter로 따로 받으신 이유가 있나요?

2023-02-27 04:12 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/persistence/JpaMemberRepository.java
> +public interface JpaMemberRepository extends JpaRepository<Member, Long> {
`JpaMemberRepository` 앞에 Jpa를 붙이신 이유가 있을까요

2023-02-27 04:13 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/domain/entity/Member.java
>      private Long id;
@JisuNa  네 수정하겠습니다.!

2023-02-27 04:16 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/persistence/JpaMemberRepository.java
> +public interface JpaMemberRepository extends JpaRepository<Member, Long> {
@JisuNa InMemoryRepository가 있어 구분자값을 위해 붙였습니다.

2023-02-27 04:18 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        String pass = command.getPassword();
@JisuNa 추후 암호화 과정이 필요할꺼 같아 따로 빼놨습니다.
변수명은 생각해보고 바꾸도록 하겠습니다.

2023-02-27 04:20 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/application/command/MemberAddCommand.java
> +    public Member toEntity(String password) {
@JisuNa 암호화 작업을 위해 따로 parameter로 받았습니다

2023-02-27 04:50 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        String pass = command.getPassword();
암호화 로직이 들어간다하더라도 password에 넣어도 되지 않을까요?

2023-02-27 04:58 UTC, JisuNa requested changes

2023-02-27 04:58 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/presentation/MemberRestController.java
> +}
컨트롤러를 인터페이스로 정의하신 이유가 있을까요

2023-02-27 04:58 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/persistence/InMemoryMemberAddRepository.java
> +        return map.put(idGenerator.incrementAndGet(), member);
전체적인 구조가 `processor` -> `InMemoryMemberAddRepository` -> `MemberRepository` 구조인거 같은데, InMemory는 디비에 저장하지 않고 메모리에 저장하기 위해 사용한 것인데, InMemory가 중간에서 하는 역할이 있을까요.

2023-02-27 05:50 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        String pass = command.getPassword();
처음에는 그렇게 생각했는데 사용자 가입시 에는 password로 받고
암호화된 데이터 구분을 위해 변수명을 encryptedPassword 로 구분점을 두는게 좋지 않을까요?

2023-02-27 05:51 UTC, gyhcom commented on starlucks-main/src/main/resources/db/migration/V1.0__init_ddl.sql
> +);
@JisuNa 네넵 읽어보고 소문자로 변경하겠습니다!

2023-02-27 05:56 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        String pass = command.getPassword();
plain text인 password가 암호화된 이후에는 사용되는 경우가 있다면 구분점이 있어야겠지만 보안상 암호화된 이후에는 사용되면 안될 것 같아요.

2023-02-27 06:38 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        String pass = command.getPassword();
@JisuNa 네네 이해했습니다. 이부분에 대해서도 다시 생각하고 수정하도록 하겠습니다.

2023-02-27 08:34 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/presentation/MemberRestController.java
> +}
아 이거는 다른 프로젝트를 참고해서 제가 써보지 않은 인터페이스를 정의해서 각 컨트롤러 마다 어노테이션 하나로 공용으로 쓰기 위해 만들어보았습니다.

2023-02-27 09:17 UTC, JisuNa commented
첫 커밋은 DB명 변경과 Flyway 적용 작업 커밋인데 PR은 회원가입 JPA 구현이네요.
PR 분리해서 올라가는게 협업 관점에서 좋아보여요.
특히 공통으로 사용되는 코드는 다른 작업자에게 영향을 줄 수 있을 것 같아요.

2023-02-27 10:14 UTC, f-lab-bright commented
flyway 스키마 적용과 기능 작업은 한 pr에서 하는게 맞습니다.
어떤 스키마 변경이 어떤 기능 추가/수정과 같이 이루어지는지를 볼 수 있어야 합니다

2023-02-27 10:16 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/presentation/MemberRestController.java
> +}
어노테이션을 상속해서 쓰는게 필요할지 한 번 고민해보세요.
/member로 시작하는 컨트롤러가 아주 많다면 이렇게 만들어 재활용하는게 도움이 되겠지만, 그렇지 않다면 크게 효과적이지 않습니다 :)

2023-02-27 10:17 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/persistence/JpaMemberRepository.java
> +public interface JpaMemberRepository extends JpaRepository<Member, Long> {
package 수준에서부터 구현체별로 구분할 수 있는 prefix가 있는게 좀 더 좋지 않을까요 :)

2023-02-27 10:19 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        String pass = command.getPassword();
코드가 진행되는 과정에 따라서 변수가 그 컨텍스트를 잘 전달할 수 있는지를 고민해보고 결정하시면 될 것 같습니다.
코드를 읽는 사람 관점에서 보면 암호화된 문자열인지 아닌지를 변수명으로 바로 알 수 있는게 가장 좋고, 그렇지 않다면 할당되는 코드들을 다 보면서 이해해야 합니다 :)

2023-02-27 10:20 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/domain/entity/Member.java
>      private Long id;
member.memberId는 중복 컨텍스트이지 않을까요?
id는 엔티티별로 유일하기 때문에 prefix를 굳이 다시 붙일 필요가 없습니다

2023-02-27 10:21 UTC, f-lab-bright commented on starlucks-main/src/main/resources/db/migration/V1.0__init_ddl.sql
> +);
이건 디비에 따라 다르긴 한데, mysql 은 소문자 + snake_case 가 일반적입니다 :)
설정에 따라 대소문자를 구분하지 않게 쓸 수도 있어서요 :)

2023-02-27 10:30 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/presentation/MemberRestController.java
> +@Retention(RetentionPolicy.RUNTIME)
RetentionPolicy가 왜 Runtime이어야 할까요?

2023-02-27 10:30 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/application/command/MemberAddCommand.java
> +    public Member toEntity(String password) {
entity로 변경하는 책임이 dto에 있는게 적적할지도 고민해봐야 할 것 같네요 :)

2023-02-27 10:30 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/domain/entity/Member.java
> +@Entity
테이블 명 지정도 잊지말고 챙겨주시는게 오류를 방지하는데 도움이 됩니다 :)

2023-02-27 10:30 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/config/MemberConfig.java
> +        return new MemberAddProcessor(memberRepository);
이 processor 부분이 jpa를 쓰면서 auto incrememt로 아이디를 할당 받으면서 변경이 생겼네요.
jpa로 바꾸면서 변경이 일어나지 않게 하려면 어떻게 책임을 할당하는게 좋았을지 고민해보면 좋을 것 같습니다 :)

2023-02-27 10:30 UTC, f-lab-bright commented on starlucks-main/src/main/resources/db/migration/V1.0__init_ddl.sql
> +
동일한 테이블을 추가하는 파일이 두 개나 있네요.
한 pr 내에서는 스키마 변경에 대해서 매번 다른 파일로 버전업 하는 것 보다 하나로 관리하는게 좀 더 좋을 것 같습니다.
테이블이 여러개 추가되는 경우에는 한 파일로 다 할지, 테이블 별로 나눌지 고민해보면 좋겠네요 :)

2023-02-27 12:47 UTC, f-lab-bright commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/memberTable.ddl
> +create table member(
이 위치에 있으면 안되긴 하겠네요

2023-02-27 12:56 UTC, f-lab-bright commented on starlucks-main/src/main/resources/db/migration/V1.0__init_ddl.sql
> +    EMAIL VARCHAR(20) NOT NULL,
이 필드는 unique해야하지 않을까요?

2023-03-01 08:15 UTC, JisuNa commented
> flyway 스키마 적용과 기능 작업은 한 pr에서 하는게 맞습니다. 어떤 스키마 변경이 어떤 기능 추가/수정과 같이 이루어지는지를 볼 수 있어야 합니다

말씀하신 것 처럼 스키자 적용은 기능 작업과 같이 있는게 맞습니다.
제 의견은 flyway 의존성 추가를 다른 PR에서 작업하는게 좋겠다는 의견이었습니다.

2023-03-01 12:24 UTC, gyhcom commented on starlucks-main/src/main/resources/db/migration/V1.0__init_ddl.sql
> +
네네 알겠습니다!

2023-03-01 12:24 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/domain/entity/Member.java
> +@Entity
네네 테이블 어노테이션 지정 하겠습니다.

2023-03-01 12:26 UTC, gyhcom reviewed
코드 리뷰해주신걸 토대로
수정하였습니다.

2023-03-01 12:28 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/domain/entity/Member.java
>      private Long id;
그럼 entity는 기존대로 가겠습니다.

2023-03-04 09:53 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        String pass = command.getPassword();
그러면 이부분도 현재 암호화된 문자열인지 아닌지를 변수명으로 바로 알수 있게
변수명을 encryptedPassword 로 선언하도록 하겠습니다.

2023-03-04 12:29 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/persistence/InMemoryMemberAddRepository.java
> +        return map.put(idGenerator.incrementAndGet(), member);
@JisuNa 현재는 역할은 없습니다. 삭제 하도록 하겠습니다.

2023-03-05 02:08 UTC, gyhcom commented on starlucks-main/src/main/resources/db/migration/V1.0__init_ddl.sql
> +    EMAIL VARCHAR(20) NOT NULL,
@f-lab-bright 유니크 하게 수정하겠습니다.

2023-03-10 14:35 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        System.out.println(encodePassword);
`System.out.println(encodePassword);` 삭제하는게 좋아보여요. 🙂

2023-03-12 14:20 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        System.out.println(encodePassword);
@JisuNa 삭제했습니다 ! :)

2023-03-12 14:56 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberAddProcessor.java
> +        System.out.println(encodePassword);
[c40f8cc](https://github.com/f-lab-edu/Starlucks/pull/22/commits/c40f8cc149b94955402ed7c45fa54fdb62931647)

이렇게 적용하신 커밋 번호를 남겨주시면 리뷰어 확인할 때 도움이 됩니다.

2023-03-12 14:58 UTC, JisuNa approved these changes

2023-03-15 06:37 UTC, merged