Feat: 회원 로그인 기능 구현중
f-lab-edu/Starlucks pull request #25
Opened 2023-03-28 07:21 UTC by gyhcom

1.Login관련 Process,Request,Command 추가
2.인증 구현(email로 인증)
3.토큰방식 인가 진행예정

2023-04-05 06:11 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/persistence/redis/RedisMemberRepository.java
> +        System.out.println("authmember =" + authMember);
로그는 삭제하도록 하겠습니다.

2023-04-09 05:57 UTC, JisuNa requested changes

2023-04-09 05:57 UTC, JisuNa commented on docker/apm-docker-compose.yml
> +    container_name: starlucks_elastic
APM 설정은 별도의 PR로 됐으면 구분하기 좋았을 것 같아요.

2023-04-09 05:57 UTC, JisuNa commented on starlucks-main/src/main/resources/db/migration/V1.1__user_role_ddl.sql
> +alter table member ADD COLUMN role varchar(100) not null comment '권한';
권한에 데이터가 길이가 큰 경우가 있을까요??

2023-04-09 05:57 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberLoginProcessor.java
> +            throw new NullPointerException("잘못된 회원입니다.");
Custom Exception으로 정의하는게 좋을 것 같습니다.

2023-04-09 05:57 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/domain/entity/Role.java
> +    ADMIN,
`Member` 모듈은 일반 사용자로 판단되는데, `MANAGER`와 `ADMIN`권한이 없어도 될 것 같습니다.
일반 사용자의 권한 구분이 필요한 경우가 있을까요??

2023-04-09 05:57 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/MemberRepositoryAdapter.java
> +            .orElseThrow(()-> new NullPointerException("가입되지 않은 회원입니다."));
Custom Exception으로 정의하는게 좋을 것 같습니다.

2023-04-09 05:57 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/config/RedisConfig.java
> +    private int redisPort;
주석되어 있는 것처럼 config를 읽어오는 게 좋을 것 같아요.

2023-04-09 05:57 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/properties/TokenProperties.java
> +}
사용되는 클래스인가요??

2023-04-09 05:57 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/membersecurity/MemberPassWordEncoder.java
> +    }
사용된 암호화 방식에 대해 설명 해주실 수 있을까요??

2023-04-09 06:01 UTC, JisuNa commented
추가적으로 `member` 테이블 생성을 다시보니 `id INT(10)`은 조금 작지 않을까 싶네요.
`id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE` 변경이 되면 좋을 것 같습니다.

2023-04-09 07:45 UTC, gyhcom commented on starlucks-main/src/main/resources/db/migration/V1.1__user_role_ddl.sql
> +alter table member ADD COLUMN role varchar(100) not null comment '권한';
긴 경우는 없을꺼 같습니다. varchar(20) 정도로 수정하겠습니다.

2023-04-09 07:45 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/application/processor/MemberLoginProcessor.java
> +            throw new NullPointerException("잘못된 회원입니다.");
Exception 따로 만들어서 지정하겠습니다.

2023-04-09 07:47 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/MemberRepositoryAdapter.java
> +            .orElseThrow(()-> new NullPointerException("가입되지 않은 회원입니다."));
네넵 알겠습니다! :)

2023-04-09 07:52 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/config/RedisConfig.java
> +    private int redisPort;
네넵 알겠습니다! :)

2023-04-09 13:26 UTC, gyhcom commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/membersecurity/MemberPassWordEncoder.java
> +    }
SpringSecurity 에서 `PasswordEncoder` 지원하는 단방향 암호화 인터페이스를 사용하였고   `BcryptPassEncoder` 구현 클래스를 통해 사용자의 비밀번호를 암호화 했습니다.

```java
암호화 메소드 -> encoder()
비밀번호 비교 메소드 -> matches()
패스워드 안전점검 -> upgradeEncoding()
```

2023-04-23 09:40 UTC, JisuNa approved these changes

2023-04-23 13:38 UTC, merged