Feature/3
f-lab-edu/Starlucks pull request #8
Opened 2023-01-29 13:47 UTC by gyhcom

Member Add Api Create

2023-01-30 10:59 UTC, f-lab-bright commented on starlucks-common/src/main/java/com/starlucks/common/Codes.java
> +        ETC("기타");
이 내용은 common에 있기에 적절하진 않을 수 있을 것 같네요.
결제나 주문 처리 자체만을 위해서는 이 정보는 필요하지 않을 수 있으니까요 :)
그리고 enum으로 만들면 추가되는 사항들에 대해서 충분히 잘 모델링하기 어렵기 때문에 enum이 아닌 entity 구조로 설계를 해보시면 좋겠네요 :)

2023-01-30 21:15 UTC, gyhcom commented on starlucks-common/src/main/java/com/starlucks/common/Codes.java
> +        ETC("기타");
넵 알겠습니다. 다시 구성하겠습니다

2023-02-05 11:02 UTC, JisuNa requested changes

2023-02-05 11:02 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/infrastructure/config/MemberRepositoryConfig.java
> +    }
Config에서 save를 구현하는 구조보다는 InMemory 만들어서 저장하는게 좋아보입니다.

2023-02-05 11:02 UTC, JisuNa commented on starlucks-member/src/main/java/com/starlucks/member/presentation/reuqest/MemberAddRequest.java
> +
개행이 많이 된 것 같네요.

2023-02-05 11:26 UTC, closed without merging

2023-02-05 11:27 UTC, f-lab-bright commented
pr은 닫지 않으셔도 되고, 해당 브랜치에서 계속 작업하셔도 됩니다! :)